backend:
  name: git-gateway
  branch: master
  squash_merges: true

# local_backend: true

media_folder: "public/images/uploads/"
public_folder: "/images/uploads/"

i18n:
  structure: multiple_folders
  locales: [al, mk]

collections:
  - name: "blog"
    label: "Blog"
    editor:
      preview: false
    label_singular: "Blog"
    folder: "content/blog"
    create: true
    filter: { field: "date", value: "desc" }
    slug: "{{slug}}"
    extension: "md"
    format: "yaml-frontmatter"
    i18n: true
    fields:
      - {
          label: "Title",
          name: "title",
          required: true,
          widget: "string",
          i18n: true,
        }
      - label: "Author"
        name: "author"
        widget: "relation"
        collection: "participants"
        search_fields: ["name"]
        value_field: "name"
        display_fields: ["name"]
        multiple: true
        i18n: duplicate
      - { label: "Date", name: "date", widget: "datetime", i18n: duplicate }
      - label: "Cover Image"
        name: "cover"
        widget: "image"
        required: true
        i18n: duplicate
        media_library:
          config:
            multiple: false
      - { label: "Body", name: "body", widget: "markdown", i18n: true }
  - name: "participants"
    label: "Participants"
    editor:
      preview: false
    label_singular: "Participants"
    folder: "content/participants"
    create: true
    identifier_field: "name"
    slug: "{{slug}}"
    extension: "md"
    format: "yaml-frontmatter"
    fields:
      - { label: "Name", name: "name", required: true, widget: "string" }
      - { label: "Year", name: "year", required: false, widget: "string" }
      - label: "Image"
        name: "image"
        widget: "image"
        required: false
        media_library:
          config:
            multiple: false
      - label: "Image 2X"
        name: "image_lg"
        widget: "image"
        required: false
        media_library:
          config:
            multiple: false
      - {
          label: "Biography",
          name: "body",
          required: false,
          widget: "markdown",
        }
  - name: "trainers"
    label: "Trainers"
    editor:
      preview: false
    label_singular: "Trainer"
    folder: "content/trainers"
    create: true
    identifier_field: "name"
    slug: "{{slug}}"
    extension: "md"
    format: "yaml-frontmatter"
    fields:
      - { label: "Name", name: "name", required: true, widget: "string" }
      - { label: "Year", name: "year", required: false, widget: "string" }
      - label: "Image"
        name: "image"
        widget: "image"
        required: true
        media_library:
          config:
            multiple: false
      - label: "Image 2X"
        name: "image_lg"
        widget: "image"
        required: true
        media_library:
          config:
            multiple: false
      - { label: "Biography", name: "body", widget: "markdown" }
  - name: "Team"
    label: "Team"
    editor:
      preview: false
    label_singular: "Team"
    folder: "content/team"
    create: true
    identifier_field: "name"
    slug: "{{slug}}"
    extension: "md"
    format: "yaml-frontmatter"
    sortable_fields: ["order"]
    fields:
      - { label: "Name", name: "name", required: true, widget: "string" }
      - {
          label: "Position",
          name: "position",
          required: false,
          widget: "string",
        }
      - {
          label: "Order",
          name: "order",
          required: true,
          value_type: int,
          min: 0,
          widget: "number",
        }
      - label: "Image"
        name: "image"
        widget: "image"
        required: true
        media_library:
          config:
            multiple: false
      - label: "Image 2X"
        name: "image_lg"
        widget: "image"
        required: true
        media_library:
          config:
            multiple: false
      - { label: "Biography", name: "body", widget: "markdown" }
